name: Publish packages
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        working-directory: ./packages
        with:
          node-version: '20.x'
      - name: 'Publish pakages if not published'
        run: |
          echo "$(cat ../.npmrc)"
          echo "$(cat .npmrc || 'nope')"
          for dir in */; do
            cd $(echo $dir | tr -d '\r')
            pkgname=$(npm pkg get name | tr -d "\"")
            pkgversion=$(npm pkg get version | tr -d "\"")
            echo "Check if ${pkgname}@${pkgversion} alredy exist..."

            notHasVersion=$(npm view ${pkgname}@${pkgversion} --silent || echo "1")
            if [ $notHasVersion -eq 1 ];
            then
              npm config set //reg.example.com/:_authToken
              npm i
              npm publish --access public
            fi
            cd ..
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

